address:
  Left_joint_arm_1: 0x01
  Left_joint_arm_2: 0x02
  Left_joint_arm_3: 0x03
  Left_joint_arm_4: 0x04
  Left_joint_arm_5: 0x05
  Left_joint_arm_6: 0x06
  Right_joint_arm_1: 0x07
  Right_joint_arm_2: 0x08
  Right_joint_arm_3: 0x09
  Right_joint_arm_4: 0x0A
  Right_joint_arm_5: 0x0B
  Right_joint_arm_6: 0x0C
  Head_joint_low: 0x0D
  Head_joint_high: 0x0E
  Claw_joint_left: 0x0F
  Claw_joint_right: 0x10
ratio:
  - [36, 36, 36, 10, 10, 10, 36, 36, 36, 10, 10, 10, 36, 36]
online:
  Left_joint_arm_1: False
  Left_joint_arm_2: False
  Left_joint_arm_3: False
  Left_joint_arm_4: False
  Left_joint_arm_5: False
  Left_joint_arm_6: False
  Right_joint_arm_1: False
  Right_joint_arm_2: False
  Right_joint_arm_3: False
  Right_joint_arm_4: False
  Right_joint_arm_5: False
  Right_joint_arm_6: False
  Head_joint_low: False
  Head_joint_high: False
  Claw_joint_left: False
  Claw_joint_right: False
parameter:
  Left_joint_arm_1: [0, 25, 2, 0, 0, 0, 0]
  Left_joint_arm_2: [0, 20, 2, 0, 0, 0, 0]
  Left_joint_arm_3: [0, 20, 2, 0, 0, 0, 0]
  Left_joint_arm_4: [0, 10, 2, 0, 0, 0, 0]
  Left_joint_arm_5: [0, 10, 2, 0, 0, 0, 0]
  Left_joint_arm_6: [0, 10, 2, 0, 0, 0, 0]
  Right_joint_arm_1: [0, 25, 2, 0, 0, 0, 0]
  Right_joint_arm_2: [0, 20, 2, 0, 0, 0, 0]
  Right_joint_arm_3: [0, 20, 2, 0, 0, 0, 0]
  Right_joint_arm_4: [0, 10, 2, 0, 0, 0, 0]
  Right_joint_arm_5: [0, 10, 2, 0, 0, 0, 0]
  Right_joint_arm_6: [0, 10, 2, 0, 0, 0, 0]
  Head_joint_low: [0, 4, 3, 0, 0, 0, 0]
  Head_joint_high: [0, 10, 6, 0, 0, 0, 0]
  Claw_joint_left: [0, 45, 1, 0, 0, 0, 0]
  Claw_joint_right: [0, 45, 1, 0, 0, 0, 0]
negtive_address:
  - [0x0D, 0x02, 0x04, 0x08, 0x0A, 0x0B, 0x09, 0x0C, 0x05]
low_arm_address:
  - [0x04, 0x05, 0x06, 0x0A, 0x0B, 0x0C]
control_mode: ptm
Multi-turn_Encoder_mode: False
zero_position:
  Left_joint_arm:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  Right_joint_arm:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  Head_joint:
    - [0.0, 0.0]